# Docker Compose override for Mac compatibility
# Use with: docker compose -f docker-compose.yml -f docker-compose.mac.yml up

services:
  rcrt:
    build:
      context: .
      dockerfile: Dockerfile.multiarch
      args:
        FEATURES: "embed-onnx nats"
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    platform: linux/amd64  # Force x64 on Apple Silicon for better compatibility
    # Additional environment variables for debugging
    environment:
      RUST_LOG: info,rcrt_server=debug
      RUST_BACKTRACE: 1
      # Explicitly set ONNX paths
      ORT_DYLIB_PATH: /usr/local/lib/libonnxruntime.so
      LD_LIBRARY_PATH: /usr/local/lib:/app/onnx/lib
